spring:
    application:
        name: barbearia
    flyway:
        enabled: true
        locations:
            - classpath:db/migration/
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 0001
        driver-class-name: org.postgresql.Driver